networks:
  side:
    driver: overlay

services:
  hexbook:
    image: hub-hexbook:latest
    ports:
      - "3016:3016"
    volumes:
      - ./.run.env:/hexbook/.run.env
      - ./assets:/hexbook/assets
      - ./_volume/_logs/hexbook_backend:/logs
    networks:
      - side
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any # no always policy on swarm mode
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        reservations:
          cpus: "0.01"
          memory: 128M
        limits:
          cpus: "0.01"
          memory: 128M